version: '3.0'
services:
  application:
    image: server
    container_name: server
    build:
        context: .
        dockerfile: docker/server.development.dockerfile
    volumes: ['.:/var/www']
    ports:
      - "8000:8000"