version: '3.0'
services:
  server1:
    image: server
    build:
        context: .
        dockerfile: docker/server.development.dockerfile
    environment:
      - APP=server1
    ports:
      - "8000:8000"