# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-04-01 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0002_auto_20210331_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
