# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-04-01 06:12
from __future__ import unicode_literals

import businesscard.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0003_auto_20210401_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(storage=businesscard.storage.PrivateMediaStorage(), upload_to=''),
        ),
    ]
