# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-04-01 22:12
from __future__ import unicode_literals

import businesscard.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0004_auto_20210401_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(storage=businesscard.storage.PrivateMediaStorage(), upload_to=''),
        ),
    ]
